name: main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
        working-directory: 07-testing
      - run: npm run test
        working-directory: 07-testing
      - run: npm run build
        working-directory: 07-testing
